# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2-elastic-search
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        deployment: wso2-elastic-search
    spec:
      initContainers:
        - name: init-wso2-elasticsearch-service
          image: busybox
          command: ['sh', '-c', 'until nc -z wso2-elasticsearch-service 9200; do echo waiting for wso2-elasticsearch-service; sleep 2; done;']
      containers:
      - name: wso2-elastic-search
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nc -z localhost 9200
          initialDelaySeconds: 20
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - nc -z localhost 9200
          initialDelaySeconds: 20
          periodSeconds: 5
        imagePullPolicy: Always
        ports:
        -
          containerPort: 9200
          protocol: "TCP"
        -
          containerPort: 9300
          protocol: "TCP"
--
apiVersion: v1
kind: Service
metadata:
  name: wso2-elasticsearch-service
spec:
  selector:
    deployment: wso2-elastic-search
  ports:
    -
      name: pass-through-http
      protocol: TCP
      port: 9200
    -
      name: pass-through-http
      protocol: TCP
      port: 9300